--- 
- 
  hosts: localhost
  name: "AWS_IBM integration via ssh keys using ansTerra"
  gather_facts: false
  vars: 
    terraform_aws_dir: "../aws"
  tasks: 
    - 
      name: "terraform aws module"
      terraform: 
        project_path: "{{terraform_aws_dir}}"
        state: present
      register: terraform_aws_outputs

